name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests

      - name: Install dependencies
        run: npm install
        
      - name: Start the application
        run: npm start &
        
      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          start: npm start
          browser: chrome
          headless: true
          
